mode: data driven # Simulation mode: "data driven" or "rule based"
location_timeseries_path: src/amr_hub_abm/data/location_timeseries.csv # Path to location timeseries data
buildings_path: src/amr_hub_abm/data/buildings.yml # Path to buildings geojson file

average_hcw_speed: 1.4 # Average speed of healthcare workers in m/s
minimum_hcw_speed: 1.0 # Minimum speed of healthcare workers in m/s
maximum_hcw_speed: 2.0 # Maximum speed of healthcare workers in m/s
